from fastapi import APIRouter, HTTPException
from app.schema import llm_schema
from app.service import vertex_ai_service

router = APIRouter(
    prefix="/llm",
    tags=["LLM Generation"]
)

@router.post("/generate", response_model=llm_schema.FullReportResponse)
def generate_text(request: llm_schema.AnalysisInput):
    """
    Accepts a prompt and returns a response generated by the Vertex AI LLM.
    """

    try:
        response_dict = vertex_ai_service.generate_full_report(request)
        
        if "error" in response_dict:
            raise HTTPException(status_code=500, detail=response_dict["error"])
        
        return response_dict

    
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred: {str(e)}")

